// src/js/audio.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class AudioManager {
  constructor() {
    this.ctx = null;
    this.masterGain = null;
    this.muted = false;
  }

  init() {
    this.ctx = null; // Created on first user gesture in real impl
    this.masterGain = null;
  }

  playSfx(_name, _intensity) {}
  setMuted(_muted) {
    this.muted = _muted;
  }
  setVolume(_value) {}
  suspend() {}
  resume() {}
}

export function createAudioManager() {
  return new AudioManager();
}
