// src/js/constants.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export const TARGET_FPS = 60;
export const STEP_MS = 1000 / 60;
export const MAX_ACCUMULATOR = 100;
export const VIRTUAL_WIDTH = 800;
export const VIRTUAL_HEIGHT = 600;

export const GAME_STATE = {
  MENU: 'MENU',
  COUNTDOWN: 'COUNTDOWN',
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  GAME_OVER: 'GAME_OVER',
};

export const DIFFICULTY = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
};

export const COLORS = {
  BACKGROUND_TOP: '#0f0c29',
  BACKGROUND_BOTTOM: '#24243e',
  PADDLE: '#00d2ff',
  BALL: '#ffffff',
};
