// src/js/game.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class Game {
  constructor(_canvas, _options) {
    this.canvas = _canvas;
    this.running = false;
    this.stateMachine = null;
  }

  init() {}
  start() {
    this.running = true;
  }
  pause() {
    this.running = false;
  }
  resume() {
    this.running = true;
  }
  stop() {
    this.running = false;
  }
  update(_dt) {}
  render(_ctx, _interpolation) {}
  changeState(_newState, _payload) {}
  checkWinCondition() {
    return false;
  }
  resetBall() {}
  resetScores() {}
}

export function createGame(canvas, options) {
  return new Game(canvas, options);
}
