// src/js/input.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class InputHandler {
  constructor(_canvas) {
    this.canvas = _canvas;
    this.keys = new Set();
  }

  init() {}
  destroy() {}
  update() {}

  getLeftPaddleTarget() {
    return 0.5;
  }
  getRightPaddleTarget() {
    return 0.5;
  }
  isPausePressed() {
    return false;
  }
  consumeAction() {
    return false;
  }
  isKeyDown(_code) {
    return false;
  }
}

export function createInput(canvas) {
  return new InputHandler(canvas);
}
