// src/js/leaderboard.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

const API_BASE_URL = '/api/v1';

export class LeaderboardClient {
  constructor(_baseUrl) {
    this.baseUrl = _baseUrl || API_BASE_URL;
  }

  async getLeaderboard(_params) {
    return { timeframe: 'all', game_mode: 'all', entries: [], total: 0, generated_at: new Date().toISOString() };
  }

  async submitScore(_payload) {
    return { success: true, entry_id: '00000000-0000-0000-0000-000000000000', rank: 1 };
  }

  async getPlayerScores(_playerName) {
    return { player_name: _playerName, best_score: 0, games_played: 0, last_played_at: new Date().toISOString() };
  }
}

export function createLeaderboardClient(baseUrl) {
  return new LeaderboardClient(baseUrl);
}
