// src/js/particles.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class ParticleSystem {
  constructor(_maxParticles) {
    this.maxParticles = _maxParticles || 200;
    this.particles = [];
  }

  spawn(_x, _y, _count, _config) {}
  update(_dt) {}
  render(_ctx) {}
  clear() {
    this.particles = [];
  }
}

export function createParticleSystem(maxParticles) {
  return new ParticleSystem(maxParticles);
}
