// src/js/physics.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class PhysicsEngine {
  constructor(_options) {
    this.ball = { x: 0, y: 0, vx: 0, vy: 0, radius: 5 };
    this.leftPaddle = { x: 0, y: 0, width: 10, height: 60 };
    this.rightPaddle = { x: 0, y: 0, width: 10, height: 60 };
  }

  update(_dt) {}
  movePaddle(_paddle, _targetY, _dt) {}
  resolveBallWallCollision() {
    return false;
  }
  resolveBallPaddleCollision(_paddle) {
    return false;
  }
  resetBall(_direction) {}
  increaseBallSpeed(_factor) {}
}

export function createPhysicsEngine(options) {
  return new PhysicsEngine(options);
}
