// src/js/renderer.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class Renderer {
  constructor(_canvas) {
    this.canvas = _canvas;
    this.ctx = null;
  }

  init() {
    this.ctx = this.canvas.getContext('2d');
  }

  resize() {}
  clear() {}
  drawBackground() {}
  drawPaddle(_paddle) {}
  drawBall(_ball, _trail) {}
  drawParticles(_particles) {}
  drawHUD(_state) {}
  drawCourtLines() {}
  render(_gameState, _interpolation) {}
}

export function createRenderer(canvas) {
  return new Renderer(canvas);
}
