// src/js/state-machine.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export function createStateMachine(initialState) {
  return {
    current: initialState,
    previous: null,
    canTransition() {
      return true;
    },
    transition(_newState, _payload) {
      this.previous = this.current;
      this.current = _newState;
    },
  };
}

export const STATE_TRANSITIONS = {};
