// src/js/state-machine.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

const VALID_TRANSITIONS = {
  BOOT: ['LOADING'],
  LOADING: ['TITLE_SCREEN'],
  TITLE_SCREEN: ['DIFFICULTY_SELECT', 'LEADERBOARD_SCREEN', 'SETTINGS_PANEL', 'TUTORIAL_OVERLAY'],
  DIFFICULTY_SELECT: ['COUNTDOWN', 'TITLE_SCREEN'],
  COUNTDOWN: ['SERVING'],
  SERVING: ['PLAYING', 'POINT_END', 'SERVING'],
  PLAYING: ['PAUSED', 'GAME_OVER', 'POINT_END'],
  PAUSED: ['PLAYING', 'TITLE_SCREEN', 'SETTINGS_PANEL'],
  POINT_END: ['NEXT_POINT'],
  NEXT_POINT: ['SERVING', 'COUNTDOWN', 'GAME_OVER'],
  GAME_OVER: ['LEADERBOARD', 'TITLE_SCREEN', 'DIFFICULTY_SELECT'],
  REPLAY: ['PLAYING'],
};

export function createStateMachine(initialState) {
  const ctx = {
    match_id: '',
    player_id: '',
    difficulty: 'novice',
    sets_to_win: 2,
    player_score: 0,
    opponent_score: 0,
    player_sets: 0,
    opponent_sets: 0,
    server: 'player_1',
    rally_count: 0,
    longest_rally: 0,
    match_start_time: '',
    point_start_time: '',
    is_replay_available: false,
  };

  const listeners = [];

  return {
    current: initialState || 'BOOT',
    previous: null,
    context: ctx,

    canTransition(newState) {
      return (VALID_TRANSITIONS[this.current] || []).includes(newState);
    },

    transition(newState, _payload) {
      if (!this.canTransition(newState)) {
        return false;
      }
      this.previous = this.current;
      this.current = newState;
      listeners.forEach(cb => cb(newState, this.previous));
      return true;
    },

    getState() {
      return this.current;
    },

    setContext(updates) {
      Object.assign(this.context, updates);
    },

    getContext() {
      return this.context;
    },

    onTransition(callback) {
      listeners.push(callback);
    },

    updateLongestRally(length) {
      if (length > this.context.longest_rally) {
        this.context.longest_rally = length;
      }
    },

    recordPoint(winner) {
      if (winner === 'player_1') {
        this.context.player_score += 1;
      } else {
        this.context.opponent_score += 1;
      }
    },
  };
}

export const STATE_TRANSITIONS = VALID_TRANSITIONS;
