// src/js/storage.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

const STORAGE_KEY = 'ppg:v1';

export class Storage {
  constructor() {
    this.data = {};
  }

  load() {
    return this.data;
  }

  save(_data) {
    this.data = _data;
  }

  getPlayerName() {
    return '';
  }

  setPlayerName(_name) {}

  getSettings() {
    return { volume: 0.8, theme: 'dark', difficulty: 'medium' };
  }

  setSettings(_settings) {}

  getLocalScores() {
    return [];
  }

  addLocalScore(_entry) {}

  getStats() {
    return { gamesPlayed: 0, wins: 0, bestCombo: 0 };
  }

  updateStats(_patch) {}
}

export function createStorage() {
  return new Storage();
}
