// src/js/ui.stub.js — auto-generated by architect
// Empty/null implementations for RED-phase test compilation.

export class UI {
  constructor(_rootElement) {
    this.root = _rootElement;
  }

  showMenu() {}
  hideMenu() {}
  showCountdown(_value) {}
  hideCountdown() {}
  showPauseMenu() {}
  hidePauseMenu() {}
  showGameOver(_score, _rank) {}
  hideGameOver() {}
  showLeaderboard(_entries) {}
  hideLeaderboard() {}
  updateScore(_left, _right) {}
  updateCombo(_combo) {}
  showToast(_message, _type) {}
}

export function createUI(rootElement) {
  return new UI(rootElement);
}
